### ISSUE TITLE
thread 'main' panicked at 'called Result::unwrap() on an Err value: Imports(Misalign)'

### ISSUE THREAD

**Issue by heySasha** [CasualX/pelite#18] opened 2018-01-25 20:08 UTC
Hi! Сould you help me?

main.rs
```
extern crate pelite;

use std::mem;

use pelite::pe64::{Pe, PeFile};

fn main () {
	let fmap = pelite::FileMap::open("hello.dll").unwrap();
	let pf = PeFile::from_bytes(&fmap).unwrap();
	unsafe {
		// ManualMap the module
		let module = pf.mmap().load().unwrap();
		println!("mapped module at {:?}", module);

		// Call an exported function as a very basic test
		let f: unsafe fn() = mem::transmute(module.offset(0x1230));
		f();
	};
}
```

hello.rs
```
#[no_mangle]
pub extern fn main() {
    println!("Hello, world!");
}
```

I get an exception:
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Imports(Misalign)', libcore\result.rs:945:5
> note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by CasualX** [comment] 2018-01-25 22:37
Please note that I quickly threw the manual mapper together and stopped when it seemed to mostly somewhat work.

That is unexpected, the error appears to come from [here](https://github.com/CasualX/pelite/blob/features/manualmap/src/mmap/windows.rs#L340). Which looks propagated from [here](https://github.com/CasualX/pelite/blob/features/manualmap/src/pe64/imports.rs#L129).

That makes it sound like the imports descriptor of your DLL is corrupt or something else is going wrong. Can I see hello.dll?

For this particular error you may try to include the "unsafe_alignment" feature which will disable alignment checking. Specified in your Cargo.toml: [link](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#choosing-features). However it'll probably just mask the underlying problem and crash.

**Comment by CasualX** [comment] 2018-01-25 23:01
Ok a quick test on my end appears to manual map hello.dll just fine (build with --release) however it crashes with an access violation when calling the function when trying to perform ThreadLocalStorage (TLS) access.

I'm aware of this issue, Rust stdlib really likes to use TLS however I my loader doesn't appear to initialize it correctly.

I cannot reproduce your alignment error.

**Comment by heySasha** [comment] 2018-01-26 00:01
Can I provide more information for reproduce my error? Thank you!

**Comment by CasualX** [comment] 2018-01-27 13:57
Alright, let's start with the obvious stuff, can you run `rustc -vV` and paste the result? The result for me is

	rustc 1.23.0 (766bd11c8 2018-01-01)
	binary: rustc
	commit-hash: 766bd11c8a3c019ca53febdcd77b2215379dd67d
	commit-date: 2018-01-01
	host: x86_64-pc-windows-msvc
	release: 1.23.0
	LLVM version: 4.0

**Comment by heySasha** [comment] 2018-01-27 14:39
```
rustc 1.25.0-nightly (ae920dcc9 2018-01-22)
binary: rustc
commit-hash: ae920dcc98c9b18b38aac03367f7f1cd6dce7d2d
commit-date: 2018-01-22
host: x86_64-pc-windows-gnu
release: 1.25.0-nightly
LLVM version: 4.0
```

**Comment by CasualX** [comment] 2018-01-27 23:33
Can you try again? I messed up the branch (it seemed to somehow got rebased on top of another feature branch) and fixed it.

I realized I can test all windows targets with AppVeyor, so I'm doing just that. Follow the CI at #12 when it's done we should get some [results](https://ci.appveyor.com/project/CasualX/pelite/build/260).

It doesn't look like it's reproducing the error either.

**Comment by heySasha** [comment] 2018-01-28 01:49
I still get a error, but when I compile main.rs with stable-x86_64-pc-windows-msvc , it is working.
And size of hello.dll with x86_64-pc-windows-gnu is too large - 4 527 kb.

**Comment by CasualX** [comment] 2018-01-28 10:21
Oooh. That line gets the rva of the export instead of hardcoding it. Your version you named the export "main", while I named it "hello". Replacing with the appropriate export name should fix that.

In any case it appears it got past the import loading, so after this change I suspect it should give the expected 0xC0000005 access violation (due to TLS not being initialized correctly).

**Comment by CasualX** [comment] 2018-01-28 15:44
If you'd like to try again, I did a crude fix to the tls issue using inline asm to get the values where they are expected. It looks like it's "working" now.

In this state the PR won't ever get merged, maybe I'll put it in a separate crate and publish it separately.

**Comment by heySasha** [comment] 2018-01-29 11:54
Yes, it's working. Thank you!

**Closed** 2018-01-29 11:57 UTC

**Comment by CasualX** [comment] 2018-01-29 18:08
Well, "working" is rather generous. Don't try to spawn any threads since their TLS won't be initialized 😄.

Doing this properly will require quite a bit of runtime that windows otherwise provides.
